services:
  - type: web
    name: expense-tracker
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: MONGO_URI
        value: mongodb+srv://spendlyuser:prasad1234@cluster0.rmlisgh.mongodb.net/?appName=Cluster0
